// Document-timeline domain model (client-safe: no node imports).
// The five standard therapy-course documents form an expected checklist —
// every patient's timeline shows them, with missing ones rendered as pending.
// Placeholder PDF templates live in templates/documents/<docType>.pdf
// (generated by scripts/generate-doc-templates.ts).
import type { DocumentRecord } from "./types";

export const DOCUMENT_TYPES = [
  "consent",
  "confidentiality",
  "emergency_contacts",
  // Filed-PDF doc type; conceptually superseded by the structured GAS goals
  // (TherapyGoal model), kept for scanned paper forms.
  "personal_goals",
  "report",
  "other",
] as const;
export type DocType = (typeof DOCUMENT_TYPES)[number];

/// The expected standard sequence, in canonical therapy-course order.
/// "report" recurs (progress/final reports), the rest are one-time intake docs.
export const STANDARD_DOC_SEQUENCE = [
  "consent",
  "confidentiality",
  "emergency_contacts",
  "personal_goals",
  "report",
] as const;

/// German clinical titles (stored on the row; clinical content stays German
/// in all UI languages, like instrument names).
export const DOC_TITLES_DE: Record<DocType, string> = {
  consent: "Einwilligungserklärung",
  confidentiality: "Vertraulichkeitserklärung",
  emergency_contacts: "Notfallkontakte",
  personal_goals: "Persönliche Therapieziele",
  report: "Therapiebericht",
  other: "Weiteres Dokument",
};

export const isDocType = (v: unknown): v is DocType =>
  typeof v === "string" && (DOCUMENT_TYPES as readonly string[]).includes(v);

export type TimelineEntry =
  | { pending: false; doc: DocumentRecord }
  | { pending: true; docType: DocType };

/// Chronological timeline: real documents sorted by clinical date, followed by
/// one pending entry per standard type that has no document yet (in the
/// canonical sequence order).
export function buildDocumentTimeline(docs: DocumentRecord[]): TimelineEntry[] {
  const real: TimelineEntry[] = [...docs]
    .sort((a, b) => Date.parse(a.occurredAt) - Date.parse(b.occurredAt))
    .map((doc) => ({ pending: false, doc }));
  const present = new Set(docs.map((d) => d.docType));
  const missing: TimelineEntry[] = STANDARD_DOC_SEQUENCE.filter((t) => !present.has(t)).map(
    (docType) => ({ pending: true, docType }),
  );
  return [...real, ...missing];
}

export function standardDocsPresent(docs: DocumentRecord[]): number {
  const present = new Set(docs.map((d) => d.docType));
  return STANDARD_DOC_SEQUENCE.filter((t) => present.has(t)).length;
}
